export let navbar = [
    {
        "role":"user",
        "name":"Home",
        "link":"/home",
    },
    {
        "role":"user",
        "name":"Forums",
        "link":"/forum",
    },
    {
        "role":"user",
        "name":"Blogs",
        "link":"/newsandblog",
    },
    {
        "role":"user",
        "name":"Videos",
        "link":"/howto",
    },
    {
        "role":"user",
        "name":"Gallery",
        "link":"/art",
    },
    {
        "role":"user",
        "name":"Shop",
        "link":"/shop",
    },
    {
        "role":"user",
        "name":"Updates",
        "link":"/updates",
    },
    {
        "role":"user",
        "name":"Community",
        "link":"/community",
    },
]